version: '3'
services:
  crazyflie_client:
    image: democrazyflie
    entrypoint: /bin/bash /crazyflie_demo/src/scripts/crazyflie_clientbridge.bash
    network_mode: "host"
    privileged: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev:/dev
    environment:
      DISPLAY: unix:0

  kobuki_gazebo:
    image: democrazyflie
    entrypoint: /bin/bash /crazyflie_demo/src/scripts/kobukigazebo.bash
    network_mode: "host"
    privileged: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      DISPLAY: unix:0
    
  kobuki_agent:
    image: microros/micro-ros-agent
    entrypoint: bash -c "source "/opt/ros/crystal/setup.bash" && source "/uros_ws/src/install/local_setup.bash" && ros2 run micro_ros_agent micro_ros_agent udp 9999 &> /dev/null < /dev/null"
    network_mode: "host"
    privileged: true

  attitude_to_vel:
    image: democrazyflie
    entrypoint: /bin/bash /crazyflie_demo/src/scripts/attitude_to_vel.bash
    network_mode: "host"
    privileged: true

  flash_crazyflie:
    image: democrazyflie
    entrypoint: /bin/bash /crazyflie_demo/src/scripts/flash_crazyflie.bash
    network_mode: "host"
    privileged: true

  keyboard_agent:
    image: democrazyflie
    entrypoint: bash -c "source "/opt/ros/dashing/setup.bash" && MicroXRCEAgent udp -p 8888"
    network_mode: "host"
    privileged: true
  
  keyboard_controller:
    image: democrazyflie
    entrypoint: /crazyflie_demo/src/kobuki_twist_keyboard_controller/kobuki_twist_keyboard_controller 127.0.0.1 8888
    network_mode: "host"
    privileged: true

  crazyflie_position_rviz:
    image: democrazyflie
    entrypoint: /bin/bash /crazyflie_demo/src/scripts/crazyflierviz_position.bash
    network_mode: "host"
    privileged: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      DISPLAY: unix:0